### ISSUE TITLE
Need following count and fans count of each following user

### ISSUE THREAD

**Issue by TTigger** [Pasdaven/Gcard#120]
<img width="833" alt="截圖 2022-12-23 上午1 48 46" src="https://user-images.githubusercontent.com/102512862/209195856-e3133111-bad0-4d76-ae05-eab0dd945d9c.png">

**Comment by TTigger** [comment]
Please add in API : Get follow user by token , thanks you !  🥇 ❤️‍🔥 ❤️ 🖤🐮💕😘

**Comment by davidho0403** [comment]
This issue has been done at #112
