### ISSUE TITLE
Follow board not working well

### ISSUE THREAD

**Issue by davidho0403** [Pasdaven/Gcard#165]
Screen recording:
https://user-images.githubusercontent.com/75478661/209426515-43a08e1b-22ad-40ac-a0f9-cbdeee701a5a.mov

**Comment by davidho0403** [comment]
Related to #152 

The codes in #152 used lots of `post` api in `frontend/src/components/board/BoardInfo.jsx`, but the page is not require any post api, please fix.

**Comment by davidho0403** [comment]
@TTigger

**Comment by TTigger** [comment]
I fix the problems , please check and tag me if there are still have problems
